title:             Khinshan Khan
email:             kkhan@stuy.edu
description:       Developer · Designer · Writer
author:            Khinshan Khan
baseurl:           ""
url:               "http://khinshankhan.com"

# Social Profiles
github_username:   kkhan01
facebook_username: khinshan.khan

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
